module "this" {
  source = "./context"

  api_key        = var.api_key
  account_id     = var.account_id
  enabled        = var.enabled
  product_domain = var.product_domain
  environment    = var.environment
  name_key_case  = var.name_key_case
  service_name   = var.service_name
  service_tags   = var.service_tags
}

variable "enabled" {
  type        = bool
  default     = true
  description = "Boolean flag to enable or disable specific module."
}

variable "account_id" {
  type        = string
  description = "New relic account ID."
}

variable "api_key" {
  type        = string
  description = "New relic API key."
}

variable "product_domain" {
  type        = string
  description = "ProductDomain on AWS."
}

variable "service_name" {
  type        = string
  description = "Name of the service."
}

variable "service_tags" {
  type        = list(string)
  description = "The service tag in New Relic. Usually marked as `Label.Service`."
}

variable "environment" {
  type        = string
  default     = null
  description = "Environment on AWS."

  validation {
    condition     = var.environment == null ? true : contains(["production", "staging", "development"], var.environment)
    error_message = "Allowed values: `production`, `staging`, `development`."
  }
}

variable "name_key_case" {
  type        = string
  default     = null
  description = <<-EOT
    Controls the letter case of the `name` generated by this module.
    Possible values: `lower`, `title`, `upper`.
    Default value: `title`.
  EOT

  validation {
    condition     = var.name_key_case == null ? true : contains(["lower", "title", "upper"], var.name_key_case)
    error_message = "Allowed values: `lower`, `title`, `upper`."
  }
}
