load_balancer:
  high_5xx_percentage:
    enabled: true
    type: "baseline"
    name: "Anomaly 5XX LB Error Percentage"
    description: "Anomaly 5XX LB error percentage"
    aggregation_delay: 60
    aggregation_window: 60
    aggregation_method: "event_flow"
    violation_time_limit_seconds: 3600
    baseline_direction: "upper_only"
    query: |
      SELECT 
        sum(`aws.applicationelb.HTTPCode_ELB_5XX_Count`) or 0
      FROM Metric
      WHERE
        label.ProductDomain='${product_domain}'
        AND label.Environment='${environment}'
        AND label.Service IN ${service}
      FACET label.Name
    critical:
      operator: "above"
      threshold: 5
      threshold_duration: 300
      threshold_occurrences: "all"
    warning:
      operator: "above"
      threshold: 3
      threshold_duration: 300
      threshold_occurrences: "all"
  high_4xx_percentage:
    enabled: true
    type: "baseline"
    name: "Anomaly 4XX LB Error Percentage"
    description: "Anomaly 4XX LB error percentage"
    aggregation_delay: 60
    aggregation_window: 60
    aggregation_method: "event_flow"
    violation_time_limit_seconds: 3600
    baseline_direction: "upper_only"
    query: |
      SELECT
        sum(`aws.applicationelb.HTTPCode_ELB_4XX_Count`) or 0
      FROM Metric
      WHERE
        label.ProductDomain='${product_domain}'
        AND label.Environment='${environment}'
        AND label.Service IN ${service}
      FACET label.Name
    critical:
      operator: "above"
      threshold: 5
      threshold_duration: 300
      threshold_occurrences: "all"
    warning:
      operator: "above"
      threshold: 3
      threshold_duration: 300
      threshold_occurrences: "all"
